global:
  resolve_timeout: 5m

receivers:
- name: "null"

- name: gmail
  email_configs:
  - to: standarddigital82@gmail.com
    from: jacobdalton6292@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: jacobdalton6292@gmail.com
    auth_password: bcyxtybrvjeltvyx
    require_tls: true
    send_resolved: true

route:
  receiver: gmail
  group_by:
  - alertname
  - namespace
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
